### ISSUE TITLE
Cannot run multiprocessed on linux

### ISSUE THREAD

**Issue by TjobberTjob** [ethz-institute-of-microbiology/fisher_py#8] opened 2022-09-19 13:06 UTC
When I run a script multiprocessed on Linux I get this telemetry dumper:

* Assertion at mono-threads.c:499, condition `result' not met
=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
=================================================================
	Native stacktrace:
=================================================================
	0x7f3f1127665d - /home/tochr/miniconda3/lib/python3.8/site-packages/../../libmonosgen-2.0.so.1 : 
	0x7f3f112769e9 - /home/tochr/miniconda3/lib/python3.8/site-packages/../../libmonosgen-2.0.so.1 : 
	0x7f3f11207bc2 - /home/tochr/miniconda3/lib/python3.8/site-packages/../../libmonosgen-2.0.so.1 : 
	0x7f3f11275ba2 - /home/tochr/miniconda3/lib/python3.8/site-packages/../../libmonosgen-2.0.so.1 : 
	0x7f3f11f7e3c0 - /lib/x86_64-linux-gnu/libpthread.so.0 : 
	0x7f3f11c5703b - /lib/x86_64-linux-gnu/libc.so.6 : gsignal
	0x7f3f11c36859 - /lib/x86_64-linux-gnu/libc.so.6 : abort
	0x7f3f1116fc2f - /home/tochr/miniconda3/lib/python3.8/site-packages/../../libmonosgen-2.0.so.1 : 
	0x7f3f1144b376 - /home/tochr/miniconda3/lib/python3.8/site-packages/../../libmonosgen-2.0.so.1 : 
	0x7f3f11465aaf - /home/tochr/miniconda3/lib/python3.8/site-packages/../../libmonosgen-2.0.so.1 : 
	0x7f3f1146613d - /home/tochr/miniconda3/lib/python3.8/site-packages/../../libmonosgen-2.0.so.1 : monoeg_assertion_message
	0x7f3f1146617b - /home/tochr/miniconda3/lib/python3.8/site-packages/../../libmonosgen-2.0.so.1 : 
	0x7f3f1145ada9 - /home/tochr/miniconda3/lib/python3.8/site-packages/../../libmonosgen-2.0.so.1 : mono_thread_info_attach
	0x7f3f113ab1e3 - /home/tochr/miniconda3/lib/python3.8/site-packages/../../libmonosgen-2.0.so.1 : 
	0x7f3f11f72609 - /lib/x86_64-linux-gnu/libpthread.so.0 : 
	0x7f3f11d33163 - /lib/x86_64-linux-gnu/libc.so.6 : clone
=================================================================
	Telemetry Dumper:
=================================================================

This only happens on linux, and happens on multiple independent linux systems.
I installed fisher-py with 'conda install -c conda-forge pythonnet' and 'pip install fisher-py' and to repoduce the error:

from time import sleep
from fisher_py import RawFile
from multiprocessing import Pool
def read_file(file):
    RawFile(file)
    sleep(10)

files = ['/path/to/file1.raw', '/path/to/file2.raw']
with Pool(2) as ps:
    list(ps.map(read_file, files))

**Comment by dowerner** [comment] 2022-10-15 15:09
Hello  @TjobberTjob 
Thank you for sharing this information and for reproducing the issue on multiple systems. At first glance it looks like an issue with Python.NET. Since we want to update to the latest Python.NET version (3.0.0) anyway I will test the new version on a linux environment with the code you provided.

**Comment by dowerner** [comment] 2022-10-15 16:25
After releasing a new version of fisher-py I have tried your code to see if the problem is resolved (test system WSL: Ubuntu 20.04). Sadly, I get the same error with the latest pythonnet version 3.0.0 and the latest mono runtime 6.12. My knowledge on the inner workings of pythonnet is very limited so I can only provide you with some ideas how to work around this issue.
- Try using .NET 6.0 instead of Mono. Since the DLL files used in this project should be .NET Standard, .NET Core 3.1, .NET 5.0 and .NET 6.0 should be able to use them. All of these runtimes are compatible with Linux systems. The only thing I don't know is if pythonnet supports anything else than Mono.
- If you are trying to setup a data processing pipeline try using an orchestrator like Airflow or Luigi. They are able to run python tasks on worker systems. I have seen setups where Python libraries which only worked on Windows where run on Windows workers that where orchestrated by Airflow servers running on Linux.

Since the issue is not something we can in the fisher-py code base I am closing it. Feel free to open a new one if you find a workaround that could be integrated in the library.

**Closed as completed by dowerner** 2022-10-15 16:25 UTC
