### ISSUE TITLE
Missing fields like  "UserLabel" and "Sequence Row Level Name"

### ISSUE THREAD

**Issue by keesh0** [ethz-institute-of-microbiology/fisher_py#6] opened 2022-07-22 17:31 UTC
Hello,
I am using this nice Python API to access raw file metadata.
Although I can easily obtain sample_information.user_text,
I cannot extract  "UserLabel" or "Sequence Row Level Name".
Do I need to add these .NET <=> Python wrappers myself?

**Comment by dowerner** [comment] 2022-07-24 11:58
Hi @keesh0,
Thank you for taking the time and opening this issue. I can confirm that the **SampleInformation** Python class does not expose **user_label** nor **sequence_row_level_name** attributes. I looked at the assemblies shipped with this Python module to see if I can add them easily:

```CSharp
#region Assembly ThermoFisher.CommonCore.Data, Version=5.0.0.71, Culture=neutral, PublicKeyToken=1aef06afb5abd953
#endregion

using ThermoFisher.CommonCore.Data.Interfaces;

namespace ThermoFisher.CommonCore.Data.Business
{
    public class SampleInformation : CommonCoreDataObject, ISampleInformation
    {
        public const int MaxUserTextColumnCount = 20;

        public SampleInformation();

        public double SampleVolume { get; set; }
        public SampleType SampleType { get; set; }
        public string ProcessingMethodFile { get; set; }
        public string Path { get; set; }
        public int RowNumber { get; set; }
        public double IstdAmount { get; set; }
        public string CalibrationFile { get; set; }
        public string RawFileName { get; set; }
        public string InstrumentMethodFile { get; set; }
        public double DilutionFactor { get; set; }
        public string CalibrationLevel { get; set; }
        public BarcodeStatusType BarcodeStatus { get; set; }
        public string Barcode { get; set; }
        public double InjectionVolume { get; set; }
        public string Vial { get; set; }
        public string SampleName { get; set; }
        public string SampleId { get; set; }
        public string Comment { get; set; }
        public double SampleWeight { get; set; }
        public string[] UserText { get; set; }
        public SampleInformation DeepCopy();
    }
}
```

As you can see from the class outline in C# the properties you are looking for are either not part of the 5.0.0.71 version of the library or there is a child class that never got instantiated with the raw-files I used for development.
Can you tell me what version of the ThermoFisher library you are using? Would it be possible for you to send me an example file that I can check if the attributes become available through a child class there? I would love to make this feature available through Python!

Best Regards,
Dominik

**Comment by keesh0** [comment] 2022-07-25 16:01
Sure.
![image](https://user-images.githubusercontent.com/13039271/180818169-0b70db3c-682a-452a-a6a3-fcd7f2468b52.png)
![image](https://user-images.githubusercontent.com/13039271/180818212-90df1575-e022-48b4-b257-af85f77cdfde.png)

I am not sure I can send one of our RAW files due to confidential patient data.
But I can try to find another example RAW file.

From a C# sample application:
![image](https://user-images.githubusercontent.com/13039271/180819153-be486feb-61bb-431d-899b-9286ef49fe6d.png)

Having trouble finding C# equiv. to C++ raw_GetSeqRowLevelName() ?

Thanks very much for your help.
e.-

**Comment by dowerner** [comment] 2022-07-25 20:11
Oh I see. My bad I thought the attribute was supposed to be on the **sample_information** object exposed by the RawFileAccess class. It turns out that it should be possible to make the attributes you mentioned available in Python:
![image](https://user-images.githubusercontent.com/14911790/180865649-85c1b0d8-581e-4822-bd0f-a729c4348bf9.png)

Please tell me exactly which attributes besides **UserLabel** and **Sequence Row Level Name** you need and I will create an update as soon as I have the time.

**Comment by keesh0** [comment] 2022-07-26 17:01
If possible, the following too:
IErrorLogEntry GetErrorLogItem(int index);
Gets an entry from the instrument error log, using a zero
based index. The number of error log entries can be
determined by RunHeaderEx.ErrorLogCount

There may be others in a few weeks as I dig deeper.

**Comment by dowerner** [comment] 2022-07-28 05:01
Perfect. I have created a branch locally and will push it as soon as I have implemented all the changes.

**Comment by dowerner** [comment] 2022-07-31 13:35
I have added the following attributes to the **RawFileAccess** class:
- auto_sampler_information
- computer_name
- user_label
- file_error
- file_header
- has_instrument_method
- has_ms_data
- scan_events
- status_log_plottable_data
Also the method **get_error_log_item** was added.
The **WrapperRunHeader** class (accessed from RawFileAccess.run_header_ex) was extended with the following attribute:
- error_log_count

I was unable to find "Sequence Row Level Name".

**Comment by dowerner** [comment] 2022-07-31 13:42
I have created and merged a PR from my feature branch. The package can now be updated via ```pip install --upgrade fisher-py```. I'm closing this issue, feel free to create a new one if you need more features :-)

**Closed as completed by dowerner** 2022-07-31 13:42 UTC
